/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mainSol from "./Main.sol";
export type { mainSol };
import type * as tokensSol from "./Tokens.sol";
export type { tokensSol };
import type * as utils from "./utils";
export type { utils };
export type { Admin } from "./Admin";
export type { Batches } from "./Batches";
export type { Products } from "./Products";
export type { Suppliers } from "./Suppliers";
