/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface IBatchesHolderInterface extends utils.Interface {
  functions: {
    "batchExists(uint256)": FunctionFragment;
    "getSupplier()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "batchExists" | "getSupplier"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "batchExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplier",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IBatchesHolder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBatchesHolderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchExists(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getSupplier(overrides?: CallOverrides): Promise<[string]>;
  };

  batchExists(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  getSupplier(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    batchExists(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    getSupplier(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    batchExists(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupplier(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    batchExists(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
