/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchesHolder } from "./BatchesHolder";
export type { IBatchesHolder } from "./IBatchesHolder";
