/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBatchesOperator,
  IBatchesOperatorInterface,
} from "../../../../contracts/utils/BatchesOperator.sol/IBatchesOperator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "addOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isOperator",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "removeOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBatchesOperator__factory {
  static readonly abi = _abi;
  static createInterface(): IBatchesOperatorInterface {
    return new utils.Interface(_abi) as IBatchesOperatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBatchesOperator {
    return new Contract(address, _abi, signerOrProvider) as IBatchesOperator;
  }
}
