/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchesOperator__factory } from "./BatchesOperator__factory";
export { IBatchesOperator__factory } from "./IBatchesOperator__factory";
