/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as batchesHolderSol from "./BatchesHolder.sol";
export * as batchesOperatorSol from "./BatchesOperator.sol";
