/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BatchesOperator } from "./BatchesOperator";
export type { IBatchesOperator } from "./IBatchesOperator";
