/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBatchesHolder,
  IBatchesHolderInterface,
} from "../../../../contracts/utils/BatchesHolder.sol/IBatchesHolder";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "batchExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupplier",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBatchesHolder__factory {
  static readonly abi = _abi;
  static createInterface(): IBatchesHolderInterface {
    return new utils.Interface(_abi) as IBatchesHolderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBatchesHolder {
    return new Contract(address, _abi, signerOrProvider) as IBatchesHolder;
  }
}
