/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchesHolder__factory } from "./BatchesHolder__factory";
export { IBatchesHolder__factory } from "./IBatchesHolder__factory";
