/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as batchesHolderSol from "./BatchesHolder.sol";
export type { batchesHolderSol };
import type * as batchesOperatorSol from "./BatchesOperator.sol";
export type { batchesOperatorSol };
